# Generated by Django 5.0.4 on 2024-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='product_image',
            new_name='proimg5',
        ),
    ]
