# Generated by Django 5.0.4 on 2024-05-03 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gla_olx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(max_length=100)),
                ('seller_id', models.CharField(default='admin', max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_picture', models.URLField()),
                ('product_status', models.CharField(max_length=50)),
                ('proimg1', models.URLField()),
                ('proimg2', models.URLField()),
                ('proimg3', models.URLField()),
                ('proimg4', models.URLField()),
                ('proimg5', models.URLField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
