# Generated by Django 5.0.4 on 2024-05-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0001_initial'),
    ]

    operations = [
    ]
