# Generated by Django 5.0.4 on 2024-05-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='product_id',
            new_name='id',
        ),
    ]
