# Generated by Django 5.0.4 on 2024-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0002_rename_product_image_productdetails_proimg5'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='seller_id',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
