# Generated by Django 5.0.4 on 2024-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0003_rename_product_id_productdetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='id',
            new_name='product_id',
        ),
    ]
