# Generated by Django 5.0.4 on 2024-05-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0002_initial'),
        ('gla_olx', '0003_initial'),
    ]

    operations = [
    ]
