# Generated by Django 5.0.4 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gla_olx', '0003_productdetails_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
